In [160]:
# Valid Sudoku

In [161]:
import numpy as np

In [162]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [163]:
s[0]

array([5, 3, 4, 6, 7, 8, 9, 1, 2])

In [164]:
np.sum(s, axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

np.sum(s, axis = 0)

In [165]:
b = np.sum(s, axis=0)
print(b)
for i in b:
    if i != 45:
        print('it is an invalid sudoku')
        break
else:
    print('it is a valid sudoku')

[45 45 45 45 45 45 45 45 45]
it is a valid sudoku


In [166]:
np.sum(s, axis=0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [167]:
c = np.sum(s, axis=1)
print(c)
for i in c:
    if i != 45:
        print('it is an invalid sudoku')
        break
else:
    print('it is a valid sudoku')

[45 45 45 45 45 45 45 45 45]
it is a valid sudoku


In [168]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [169]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3, j:j+3]
        print(n)
        if n.sum() != 45:
            print('it is an invalid sudoku')
            break
        print()
else:
    print('it is a valid sudoku')

[[5 3 4]
 [6 7 2]
 [1 9 8]]

[[6 7 8]
 [1 9 5]
 [3 4 2]]

[[9 1 2]
 [3 4 8]
 [5 6 7]]

[[8 5 9]
 [4 2 6]
 [7 1 3]]

[[7 6 1]
 [8 5 3]
 [9 2 4]]

[[4 2 3]
 [7 9 1]
 [8 5 6]]

[[9 6 1]
 [2 8 7]
 [3 4 5]]

[[5 3 7]
 [4 1 9]
 [2 8 6]]

[[2 8 4]
 [6 3 5]
 [1 7 9]]

it is a valid sudoku


In [170]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [171]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [172]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [173]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [174]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [175]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]

array([[19, 92, 88]])

In [176]:
#Increase Math marks of all students by 5.
# data[:,1] = data[:,1] + 5
data[:,1] + 5

array([90, 97, 81, 70, 95])

In [177]:
#Find how many students are younger than 19.
len(data[data[:,0] < 19])

3

In [178]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:3], axis=0)


array([81.6, 83.2])

In [179]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >=80) & (data[:,2] >=80)]



array([[19, 92, 88],
       [20, 90, 85]])

In [180]:
#Replace all Science marks < 75 with 0.

In [183]:
data[:,2][data[:,2] < 75] = 0

In [184]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])